# -*- coding: utf-8 -*-
"""battery-problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtjP1KqIwVfaapOQzUwKUufWPkL4PMUV

Fred is a very predictable man. For instance, when he uses his laptop, all he does is watch TV shows. He keeps on watching TV shows until his battery dies. Also, he is a very meticulous man, i.e. he pays great attention to minute details. He has been keeping logs of every time he charged his laptop, which includes how long he charged his laptop for and after that how long was he able to watch the TV. Now, Fred wants to use this log to predict how long will he be able to watch TV for when he starts so that he can plan his activities after watching his TV shows accordingly.

Challenge

You are given access to Fred’s laptop charging log by reading from the file “trainingdata.txt”. The training data file will consist of 100 lines, each with 2 comma-separated numbers.

The first number denotes the amount of time the laptop was charged.
The second number denotes the amount of time the battery lasted.
The training data file can be downloaded here (this will be the same training data used when your program is run). The input for each of the test cases will consist of exactly 1 number rounded to 2 decimal places. For each input, output 1 number: the amount of time you predict his battery will last.

Sample Input

1.50

Sample Output

3.00
"""

#!/bin/python3

import math
import os
import random
import re
import sys

# read training data
with open("./sample_data/trainingdata.txt", "r") as f:
  data = [line.strip() for line in f.readlines() if line.strip()]
  print(data)

# parse data and remove clipped entries (like battery lasted max time)
dataset = []
for line in data:
  x_str, y_str = line.split(',')
  x, y = float(x_str), float(y_str)
  if y < 8.0: #ignore full charge
    dataset.append((x, y))

#linear regression

n = len(dataset)
sum_x = sum(x for x, y in dataset)
sum_y = sum(y for x, y in dataset)
sum_xy = sum(x * y for x, y in dataset)
sum_xx = sum(x * x for x, y in dataset)

# avoid zero div

if n == 0 or (n * sum_xx - sum_x ** 2) == 0:
  print("No solution")
  m = 0
  b = 0
else:
  m = (n * sum_xy - sum_x * sum_y) / (n * sum_xx - sum_x ** 2)
  b = (sum_y - m * sum_x) / n

# read the input (charging time) and predict
input_time = float(input().strip())
predicted = m * input_time + b
# capp to 8h
print(round(min(predicted, 8.0), 2))